package io.flatzen.viewmodel.filter

/**
 * Presentation-side mirror of [entities.MetroLine]. Keep in sync when adding lines.
 */
enum class MetroLineState {
    GREEN, BLUE, RED,

    BAKERLOO, CENTRAL, CIRCLE, DISTRICT, HAMMERSMITH_CITY, JUBILEE,
    METROPOLITAN, NORTHERN, PICCADILLY, VICTORIA, WATERLOO_CITY, ELIZABETH,

    WIEN_U1, WIEN_U2, WIEN_U3, WIEN_U4, WIEN_U6,

    SEOUL_1, SEOUL_2, SEOUL_3, SEOUL_4, SEOUL_5, SEOUL_6, SEOUL_7, SEOUL_8, SEOUL_9,

    BERLIN_U1, BERLIN_U2, BERLIN_U3, BERLIN_U4, BERLIN_U5,
    BERLIN_U6, BERLIN_U7, BERLIN_U8, BERLIN_U9,
    BERLIN_S1, BERLIN_S2, BERLIN_S3, BERLIN_S5, BERLIN_S7, BERLIN_S9,

    MADRID_1, MADRID_2, MADRID_3, MADRID_4, MADRID_5, MADRID_6,
    MADRID_7, MADRID_8, MADRID_9, MADRID_10, MADRID_11, MADRID_12, MADRID_R,

    BCN_L1, BCN_L2, BCN_L3, BCN_L4, BCN_L5, BCN_L9N, BCN_L9S, BCN_L10, BCN_L11,

    BKK_BTS_SUKHUMVIT, BKK_BTS_SILOM, BKK_MRT_BLUE, BKK_MRT_PURPLE, BKK_ARL,

    TOKYO_GINZA, TOKYO_MARUNOUCHI, TOKYO_HIBIYA, TOKYO_TOZAI, TOKYO_CHIYODA,
    TOKYO_YURAKUCHO, TOKYO_HANZOMON, TOKYO_NAMBOKU, TOKYO_FUKUTOSHIN,
    TOKYO_ASAKUSA, TOKYO_MITA, TOKYO_SHINJUKU, TOKYO_OEDO,
    TOKYO_YAMANOTE,

    PARIS_M1, PARIS_M2, PARIS_M3, PARIS_M4, PARIS_M5, PARIS_M6, PARIS_M7,
    PARIS_M8, PARIS_M9, PARIS_M10, PARIS_M11, PARIS_M12, PARIS_M13, PARIS_M14,
    PARIS_RER_A, PARIS_RER_B,
}
