package io.flatzen.commoncomponents

enum class DrawablePath(val value: String) {
    OUTLINE_NOTIFICATIONS("drawable/outline_notifications.svg"),
    SORT("drawable/sort.svg"),
    GRID("drawable/grid.svg"),
    LIST("drawable/list.svg"),
    TELEGRAM("drawable/telegram.svg"),
    SWIPE_CARDS("drawable/swipe_cards.svg"),
    COPY("drawable/copy.svg"),
    METRO_STATION("drawable/metro_station.svg"),
    AREA_ON_MAP("drawable/area_on_map.webp"),
    SAVE_AREAS("drawable/save_areas.svg"),
    MY_ADBANNER("drawable/my_adbanner.webp"),
    EYE("drawable/eye.webp"),

    ONLINER32("drawable/onliner32.webp"),
    KUFAR32("drawable/kufar32.webp"),
    REALT32("drawable/realt32.webp"),
    DOMOVITA32("drawable/domovita32.webp"),
    OTODOM32("drawable/otodom32.webp"),
    OLXPL32("drawable/olxpl32.webp"),
    GRATKA32("drawable/gratka32.webp"),
    MORIZON32("drawable/morizon32.webp"),
    SSGE32("drawable/ssge32.webp"),
    LIVO32("drawable/livo32.webp"),
    BINEBI32("drawable/binebi32.webp"),
    KRISHA32("drawable/krisha32.webp"),
    OLXKZ32("drawable/olxkz32.webp"),
    KN32("drawable/kn32.webp"),
    FOTOCASA32("drawable/fotocasa32.webp"),
    PISOS32("drawable/pisos32.webp"),
    IS2432("drawable/is2432.webp"),
    IMMOWELT32("drawable/immowelt32.webp"),
    KLEINANZEIGEN32("drawable/kleinanzeigen32.webp"),
    EMLAKJET32("drawable/emlakjet32.webp"),
    PROPERTYFINDER32("drawable/propertyfinder32.webp"),
    DUBIZZLE32("drawable/dubizzle32.webp"),
    OPENSOOQ32("drawable/opensooq32.webp"),
    PROPERTYHUB32("drawable/propertyhub32.webp"),
    LIVINGINSIDER32("drawable/livinginsider32.webp"),
    RENTHUB32("drawable/renthub32.webp"),
    ZUMPER32("drawable/zumper32.webp"),
    DABANG32("drawable/dabang32.png"),
    ZIGBANG32("drawable/zigbang32.png"),
}
